# Generated by Django 2.2.1 on 2019-06-22 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190622_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pic',
            field=models.ImageField(default='download.png', upload_to='profile_pic'),
        ),
    ]
