# Generated by Django 2.2.1 on 2019-07-13 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tutor',
            field=models.BooleanField(),
        ),
    ]
