# Generated by Django 2.2.1 on 2019-06-26 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190622_1623'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='identity',
            new_name='tutor',
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(default='0404040404', max_length=30),
        ),
    ]
