# Generated by Django 2.2.1 on 2019-06-26 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='title',
            field=models.CharField(default='Hey, I am here to help you', max_length=100),
        ),
    ]
